import { Injectable } from "@angular/core";

import { Item } from "./item";

@Injectable()
export class ItemService {
    private items = new Array<Item>(
        { "id": 1, "contact": "Cornelius Sarre", "company": "Homenick-Farrell", "email": "csarre0@ibm.com", "address": "8 Oxford Lane", "lat": 40.9539, "lng": 45.61942, "phone": "335-345-9388", "severity": 1, "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.", "title": "vestibulum quam sapien varius ut blandit" },
        { "id": 2, "contact": "Markus Grundey", "company": "Bayer-Rutherford", "email": "mgrundey1@ucla.edu", "address": "46804 Hazelcrest Circle", "lat": 11.5716154, "lng": 9.1096477, "phone": "315-688-8039", "severity": 1, "description": "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.", "title": "penatibus et magnis dis parturient montes nascetur" },
        { "id": 3, "contact": "Devan Maund", "company": "Barrows, Bergnaum and Hettinger", "email": "dmaund2@alexa.com", "address": "31227 Artisan Alley", "lat": 24.7048435, "lng": -77.7852575, "phone": "550-466-5128", "severity": 3, "description": "Praesent id massa id nisl venenatis lacinia.", "title": "cubilia curae mauris viverra diam vitae quam" },
        { "id": 4, "contact": "Gregorius Candlish", "company": "Lebsack-Stroman", "email": "gcandlish3@mysql.com", "address": "91 Graceland Street", "lat": 40.0228023, "lng": 22.2409253, "phone": "907-962-1102", "severity": 3, "description": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.", "title": "augue quam sollicitudin vitae consectetuer eget rutrum at" },
        { "id": 5, "contact": "Lesli Tattersdill", "company": "Bauch, Littel and Lesch", "email": "ltattersdill4@mapquest.com", "address": "4 Prairieview Trail", "lat": 30.2638032, "lng": 102.8054753, "phone": "337-121-3688", "severity": 2, "description": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.", "title": "id ligula suspendisse ornare consequat lectus in" },
        { "id": 6, "contact": "Jude Zucker", "company": "Walker, Glover and Considine", "email": "jzucker5@google.ru", "address": "590 Butternut Park", "lat": 13.2944016, "lng": -4.8987523, "phone": "368-929-4847", "severity": 1, "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.", "title": "quis orci nullam molestie nibh in lectus" },
        { "id": 7, "contact": "Goldina Swyn", "company": "Pollich and Sons", "email": "gswyn6@dmoz.org", "address": "309 School Circle", "lat": 27.692542, "lng": 111.664316, "phone": "459-806-4738", "severity": 3, "description": "Morbi a ipsum. Integer a nibh.", "title": "vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet" },
        { "id": 8, "contact": "Donn Emons", "company": "Christiansen-Prohaska", "email": "demons7@shareasale.com", "address": "6 Old Gate Alley", "lat": 38.656021, "lng": -27.268149, "phone": "524-586-5579", "severity": 3, "description": "Nulla tempus.", "title": "dolor quis odio consequat" },
        { "id": 9, "contact": "Zonda Steiner", "company": "Schmidt, Dietrich and Steuber", "email": "zsteiner8@symantec.com", "address": "79204 Carioca Place", "lat": 51.532126, "lng": 92.8882656, "phone": "625-776-5421", "severity": 1, "description": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.", "title": "pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus" },
        { "id": 10, "contact": "Ben Plak", "company": "VonRueden, Marks and Bernhard", "email": "bplak9@dedecms.com", "address": "1 Algoma Court", "lat": 36.7558101, "lng": 41.3986916, "phone": "910-352-8087", "severity": 3, "description": "Nulla ac enim.", "title": "a feugiat et eros vestibulum ac est lacinia" },
        { "id": 11, "contact": "Edi Zanini", "company": "Dicki Inc", "email": "ezaninia@abc.net.au", "address": "63841 Acker Avenue", "lat": 4.168711, "lng": -76.167375, "phone": "773-714-1952", "severity": 1, "description": "Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.", "title": "amet erat nulla tempus vivamus in felis eu sapien" },
        { "id": 12, "contact": "Case Alpin", "company": "Jakubowski, Medhurst and Franecki", "email": "calpinb@nature.com", "address": "59699 Clemons Terrace", "lat": 58.1494235, "lng": 38.2144331, "phone": "278-487-5839", "severity": 1, "description": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.", "title": "sit amet cursus id turpis" },
        { "id": 13, "contact": "Karyn Dinsale", "company": "Conroy, Osinski and Quitzon", "email": "kdinsalec@boston.com", "address": "0 Forest Dale Parkway", "lat": 25.5025179, "lng": 49.5999539, "phone": "514-426-4465", "severity": 2, "description": "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.", "title": "amet erat nulla tempus vivamus" },
        { "id": 14, "contact": "Andeee Feldklein", "company": "Hills LLC", "email": "afeldkleind@virginia.edu", "address": "44 Fair Oaks Park", "lat": 13.460657, "lng": -15.5225259, "phone": "446-165-6536", "severity": 3, "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.", "title": "est congue elementum in hac habitasse platea dictumst morbi" },
        { "id": 15, "contact": "Valentijn Meyrick", "company": "Schultz, Goyette and Greenfelder", "email": "vmeyricke@yale.edu", "address": "383 Stone Corner Road", "lat": 6.7885037, "lng": 124.8730516, "phone": "912-967-2299", "severity": 2, "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.", "title": "eleifend quam a odio in hac habitasse" },
        { "id": 16, "contact": "Eryn Shepland", "company": "Schulist and Sons", "email": "esheplandf@uiuc.edu", "address": "0 Lakeland Road", "lat": -16.1073563, "lng": 46.6463975, "phone": "635-730-4718", "severity": 3, "description": "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.", "title": "dis parturient montes nascetur ridiculus mus vivamus" },
        { "id": 17, "contact": "Yetty Skellorne", "company": "Fadel-Deckow", "email": "yskellorneg@cyberchimps.com", "address": "36619 Chive Hill", "lat": 52.6915552, "lng": 1.6993747, "phone": "478-286-5049", "severity": 1, "description": "Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.", "title": "ac leo pellentesque ultrices mattis odio donec vitae nisi nam" },
        { "id": 18, "contact": "Porty Riddel", "company": "Schultz, Ondricka and Kulas", "email": "priddelh@cdc.gov", "address": "8932 Melrose Junction", "lat": -6.7115834, "lng": 111.3947978, "phone": "350-550-2706", "severity": 2, "description": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.", "title": "lacinia nisi venenatis tristique" },
        { "id": 19, "contact": "Dyana Henric", "company": "Greenholt-Lakin", "email": "dhenrici@gov.uk", "address": "22973 Mayfield Point", "lat": 35.26364, "lng": 116.449839, "phone": "948-748-7392", "severity": 1, "description": "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.", "title": "arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean" },
        { "id": 20, "contact": "Norby Yatman", "company": "Weber-Hintz", "email": "nyatmanj@reverbnation.com", "address": "898 Karstens Lane", "lat": 59.2669111, "lng": 17.8885705, "phone": "428-408-1803", "severity": 3, "description": "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.", "title": "nulla pede ullamcorper augue" },
        { "id": 21, "contact": "Amanda Havard", "company": "Gorczany-Flatley", "email": "ahavardk@sogou.com", "address": "173 Kennedy Avenue", "lat": 29.985295, "lng": 122.207215, "phone": "838-116-4922", "severity": 1, "description": "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.", "title": "phasellus in felis donec semper sapien a libero" },
        { "id": 22, "contact": "Glynda Simeoli", "company": "Orn, Wilderman and Maggio", "email": "gsimeolil@google.co.uk", "address": "14 Fair Oaks Terrace", "lat": 35.1595989, "lng": -106.566764, "phone": "639-170-9684", "severity": 1, "description": "Aenean sit amet justo.", "title": "metus vitae ipsum aliquam non" },
        { "id": 23, "contact": "Yuri Ahrenius", "company": "Renner-Rodriguez", "email": "yahreniusm@bluehost.com", "address": "70 Grim Parkway", "lat": -1.2457596, "lng": 102.2261837, "phone": "939-613-7501", "severity": 3, "description": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.", "title": "vestibulum ante ipsum primis in faucibus" },
        { "id": 24, "contact": "Star Angrave", "company": "Kub Group", "email": "sangraven@weather.com", "address": "59 Carioca Junction", "lat": -7.36795, "lng": 108.21101, "phone": "322-259-7443", "severity": 2, "description": "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.", "title": "ipsum primis in faucibus orci luctus et ultrices posuere cubilia" },
        { "id": 25, "contact": "Annice Katz", "company": "Yost, Will and Dooley", "email": "akatzo@ustream.tv", "address": "99720 Summerview Place", "lat": 55.6383075, "lng": 22.938485, "phone": "721-274-4580", "severity": 1, "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.", "title": "at velit eu est congue elementum in hac" },
    );

    getItems(): Promise<Item[]> {
        return new Promise((resolve, reject) => {
            resolve(this.items);
        });
    }

    getItem(id: number): Item {
        return this.items.filter(item => item.id === id)[0];
    }
}
